### ISSUE TITLE
Discrepancy Between this and egui_toast

### ISSUE THREAD

**Issue by MinaMatta98** [ItsEthra/egui-notify#14]
Hello,

I would like to add that one of the reasons I have chosen this crate instead of egui_toasts, is that egui_toasts impl !Send and !Sync for Toasts, whereas this crate does not. 

This means that I can move an Arc<Mutex<Toasts>> into a closure and await a response, from, let's say ehttp.

I think you should add this to the descriptor as it is a huge bonus on egui_toast

**Comment by ItsEthra** [comment]
Thanks for the feedback, I apologize for not replying earlier.
