### ISSUE TITLE
RichText or Font Size

### ISSUE THREAD

**Issue by mxyns** [ItsEthra/egui-notify#15]
I encountered the problem of the Toasts being too wide on smaller screens because the default font size is very big
I think it would be nice if ToastOptions included a way to customize font sizes
Another option would be to allow using egui::RichText as a caption instead

**Comment by ItsEthra** [comment]
I think the approach to use RichText as a caption is more flexible so I'll implement that.

**Comment by ItsEthra** [comment]
Finished with https://github.com/ItsEthra/egui-notify/commit/b2041159fa9bf743688f1a28348bd27d7e0e3dce but without RichText, only FontId.
