### ISSUE TITLE
Cargo run Error 

### ISSUE THREAD

**Issue by KendrickFerguson** [ItsEthra/egui-notify#20]
after follow all steps when i run this project with cargo run this error appear 

cargo run     
   Compiling my-tauri-app v0.1.0 (D:\Testing Repo\my-tauri-app)
error[E0425]: cannot find value `toasts` in this scope
 --> src\main.rs:6:5
  |
6 |     toasts.info("Hello world!").set_duration(Duration::from_secs(5));
  |     ^^^^^^ not found in this scope

error[E0425]: cannot find value `toasts` in this scope
 --> src\main.rs:8:5
  |
8 |     toasts.show(ctx);
  |     ^^^^^^ not found in this scope

error[E0425]: cannot find value `ctx` in this scope
 --> src\main.rs:8:17
  |
8 |     toasts.show(ctx);
  |                 ^^^ not found in this scope

warning: unused import: `egui_notify::Toasts`
 --> src\main.rs:1:5
  |
1 | use egui_notify::Toasts;
  |     ^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

For more information about this error, try `rustc --explain E0425`.
warning: `my-tauri-app` (bin "my-tauri-app") generated 1 warning
error: could not compile `my-tauri-app` (bin "my-tauri-app") due to 3 previous errors; 1 warning emitted

**Comment by ItsEthra** [comment]
You need to create `Toasts` instance once somewhere in your application and then call methods on it.

**Comment by KendrickFerguson** [comment]
Certainly, I have another question. Will this function in an exclusive full-screen overlay at the top? like league of legends, DOTA 2 e.t.c

**Comment by ItsEthra** [comment]
I don't know. I have only only used the library in standalone eframe applications.
