### ISSUE TITLE
[Feature request] Hold on hover

### ISSUE THREAD

**Issue by red-avtovo** [ItsEthra/egui-notify#24]
Hey!
First of all, thank you very much for such a nice library, that I really enjoy using in my project.
It would be awesome if I could hover a mouse on a toast and it could freeze both the timer and the progress bar so I could slowly read the output and once I remove my mouse from the toast it may continue and eventually destroy itself

**Comment by ItsEthra** [comment]
Hi, I agree that might be a useful feature. It seems to be pretty straight forward to implement. Relevant code here: https://github.com/ItsEthra/egui-notify/blob/2855ed2da1f4de1ee02349f1786cac2b1b13ca1d/src/lib.rs#L215-L221

I'm somewhat busy at the moment but if you are willing to implement it yourself I'll happily accept a PR.

**Comment by red-avtovo** [comment]
Thanks for implementing this 🫶
