### ISSUE TITLE
[Feature Request] add option to set background colors for toast

### ISSUE THREAD

**Issue by daBlesr** [ItsEthra/egui-notify#32]
Hi, thank you for providing this crate.
I find the toasts difficult to see/notice as there is little contrast with the background color of the app. 
Possible ways to make the toasters more noticeable: 
* I'd like to be able to configure that e.g. for success toasters the entire background of the toaster becomes green.
* Configure shadow or border.

Is this something you agree with?

**Comment by woelper** [comment]
Very good idea. A shadow would work well I suppose! I also just ran into an issue where the toast was barely visible.

**Comment by woelper** [comment]
I opened a PR with optional shadow support:
https://github.com/ItsEthra/egui-notify/pull/33
