### ISSUE TITLE
Toasts do not respect light theme

### ISSUE THREAD

**Issue by Speak2Erase** [ItsEthra/egui-notify#6]
When using light theme or any other custom theme toasts stick to a dark aesthetic
![image](https://user-images.githubusercontent.com/54482069/192324278-16b254e2-5a9d-40c5-9f1d-596e755520f3.png)

**Comment by ItsEthra** [comment]
I have little experience with egui, especially with styling, so If anybody wants to help with this, I will be grateful.

**Comment by ItsEthra** [comment]
Fixed with https://github.com/ItsEthra/egui-notify/commit/3775faec5f446a1a6fd31fe552a43a307e72a3ff
