### ISSUE TITLE
Icons get stretched on multiline notifications

### ISSUE THREAD

**Issue by inact1v1ty** [ItsEthra/egui-notify#7]
For multiline notifications the icon scales for each line, getting absurdly big with 3+ lines.

<img width="950" alt="Screenshot 2022-10-13 at 21 08 32" src="https://user-images.githubusercontent.com/16295470/195687851-a2c8f325-b32b-4034-b888-c11e779d47d5.png">

**Comment by n00kii** [comment]
i believe that is due to https://github.com/ItsEthra/egui-notify/pull/5, i have a fork which makes this a bit better if you wanna try it

**Comment by sy1ntexx** [comment]
It'll try to fix it in the next couple of days

**Comment by ItsEthra** [comment]
Should be fixed with https://github.com/ItsEthra/egui-notify/commit/4d02802ea44b305da47626af6aa39ec5491ed769
