### ISSUE TITLE
set clickable option?

### ISSUE THREAD

**Issue by matthiasdebernardini** [ItsEthra/egui-notify#8]
I'd like to be able to click a notification then copy the caption text to my clipboard.

I don't see from the API how to dismiss the notification by dismissing it. 

Is there a way to capture that clicking event?

**Comment by ItsEthra** [comment]
The first feature could be easily added however I don't quite understand your second case. And there is no way yet to add execute some code when some notification is dismissed.

**Comment by matthiasdebernardini** [comment]
*I don't see from the API how to dismiss the notification by clicking on it.

Is what I meant. 

> And there is no way yet to add execute some code when some notification is dismissed.

I am working around it now by having a button called "Dismiss and copy text" which copies the text over when the notification is dismissed. Or did you mean something else?

**Comment by ItsEthra** [comment]
> I don't see from the API how to dismiss the notification by clicking on it.
You can call `.set_closable(true)` when adding a new toast to be able to dismiss it.

But for now there is no way to copy the caption of the notification, these notifications were intended for short messages. What is your usecase for copying notification's caption?

**Comment by matthiasdebernardini** [comment]
> What is your usecase for copying notification's caption

The app produces an ID that is searchable online, so I want the user to be able to use the app and immediately be able to go online and paste the string into a search engine. 

It is an UX optimization of sorts (I could simply just print the text on the GUI and have them copy it that way) but its something other apps in this category don't do and so I thought it would be nice if mine did just to cut down on steps.

It's not a big deal, was just curious if it would be possible but it seems like "the juice is not worth the squeeze". Thanks for your help regardless.
